# Generated by Django 3.1.7 on 2021-03-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbsnote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contetnt',
            new_name='content',
        ),
    ]
